# Generated by Django 5.2.17 on 2026-10-03 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_reservationservice_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='guests_men',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reservation',
            name='guests_women',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
