# Generated by Django 5.2.17 on 2026-10-03 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_eventtype'),
        ('reservations', '0003_reservation_guests_men_reservation_guests_women'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='event_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='catalog.eventtype'),
        ),
    ]
