# Generated by Django 5.2.17 on 2026-10-03 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_reservation_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='guests_children',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
