# Generated by Django 5.2.17 on 2026-10-02 23:11

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Dar El Afrah', max_length=150)),
                ('company_phone', models.CharField(blank=True, max_length=40)),
                ('company_email', models.EmailField(blank=True, max_length=254)),
                ('company_address', models.CharField(blank=True, max_length=255)),
                ('min_confirmation_payment', models.DecimalField(decimal_places=2, default=Decimal('20000'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('allow_multiple_events_per_day', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paramètres',
                'verbose_name_plural': 'Paramètres',
                'constraints': [models.CheckConstraint(condition=models.Q(('min_confirmation_payment__gte', 0)), name='settings_min_payment_not_negative')],
            },
        ),
    ]
