# Generated by Django 5.2.17 on 2026-10-03 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='company_name_ar',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
