# Generated by Django 5.2.17 on 2026-10-03 00:37

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fr', models.CharField(max_length=120)),
                ('name_ar', models.CharField(max_length=120)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='catalog.extraservice')),
            ],
            options={
                'ordering': ['price', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OccasionPriceTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_guests', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('occasion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='catalog.occasion')),
            ],
            options={
                'ordering': ['max_guests'],
                'constraints': [models.UniqueConstraint(fields=('occasion', 'max_guests'), name='unique_tier_per_occasion')],
            },
        ),
    ]
