# Generated by Django 5.2.17 on 2026-10-03 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_serviceoption_occasionpricetier'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fr', models.CharField(max_length=120)),
                ('name_ar', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "Type d'occasion",
                'ordering': ['-is_active', 'name_fr'],
                'abstract': False,
            },
        ),
    ]
