# Generated by Django 5.2.17 on 2026-10-03 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='id_card_issued_at',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='client',
            name='id_card_issued_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='id_card_number',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
