# Generated by Django 5.2.17 on 2026-10-04 17:09

import apps.clients.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_id_card_issued_at_client_id_card_issued_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='id_document',
            field=models.FileField(blank=True, upload_to=apps.clients.models.id_document_path),
        ),
    ]
